language: java
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
  - oraclejdk8

before_install: sudo rm /etc/mavenrc
install: mvn clean verify -B -U -PenableCoverage,travis -Dmaven.main.skip=true -Dmaven.test.skip=true -Dinvoker.skip=true
script: mvn verify -B -T 1C -PenableCoverage,travis
after_success:
  - mvn jacoco:report coveralls:jacoco