language: java
install: mvn clean verify -B -U -Ptravis -Dmaven.main.skip=true -Dmaven.test.skip=true -Dinvoker.skip=true
script:
  - echo $MAVEN_OPTS
  - mvn verify -B -T 1C -PenableCoverage,travis -Dinvoker.skip=true
  - mvn invoker:install -B -T 1C -PenableCoverage,travis
  - mvn jacoco:prepare-agent-integration invoker:integration-test -B -T 1C -PenableCoverage,travis -X -Djacoco.propertyName=invoker.mavenOpts
  - mvn invoker:report -B -T 1C -PenableCoverage,travis
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
  - oraclejdk8
after_success:
  - mvn jacoco:report coveralls:jacoco
  - mvn jacoco:report-integration coveralls:jacoco -DcoverageFile=\${project.reporting.outputDirectory}/jacoco-it/jacoco.xml
