language: java
install: "mvn clean"
script: "mvn verify -T 1C"
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
branches:
  only:
    - master
after_success:
  - mvn clean test jacoco:report coveralls:jacoco
