language: java
install: "mvn clean package -B -U -Dmaven.main.skip=true -Dmaven.test.skip=true -Dinvoker.skip=true"
script: "mvn verify -B -T 1C"
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
  - oraclejdk8
