sudo: false
language: java
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7
  - oraclejdk8

cache:
  apt: false
  bundler: false
  directories:
    - $HOME/.m2/repository
before_cache: rm -rf $HOME/.m2/repository/de/is24/mavenplugins/deadcode4j-maven-plugin/

before_install:
  # https://github.com/travis-ci/travis-ci/issues/1689 & https://github.com/travis-ci/travis-ci/issues/4613
  - export MAVEN_SKIP_RC=true

install:
  #attempt to download all dependencies in the install phase; due to http://jira.codehaus.org/browse/MDEP-82, dependency:go-offline is useless
  - mvn -B -U clean verify org.apache.maven.plugins:maven-war-plugin:2.4:help -Dinvoker.skip=true -Dmaven.main.skip=true -Dmaven.plugin.skip=true -Dmaven.test.skip=true -PenableCoverage,travis
  # surefire seems to add these dependencies dynamically
  - mvn -B dependency:get -Dartifact=org.apache.maven.surefire:surefire-junit4:2.17
  - mvn -B dependency:get -Dartifact=org.apache.maven.surefire:surefire-junit47:2.17
script: mvn -B -o clean verify -PenableCoverage,travis
after_success: mvn -B jacoco:report coveralls:jacoco

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/217ded7d3afc66dca26a
    on_success: always
    on_failure: always
    on_start: false
